theme = "ronin"

[editor]
middle-click-paste = false
cursorline = true
true-color = true
color-modes = true
line-number = "relative"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer"]
idle-timeout = 5
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = true # ignore hidden

[editor.lsp]
auto-signature-help = true
snippets = false

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "→"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

# https://docs.helix-editor.com/keymap.html#select--extend-mode
# https://github.com/helix-editor/helix/blob/b58899bc8e0f339fd83a1740a896fcc62976f7a7/helix-term/src/commands.rs#L197
[keys.normal]
"A-e"     = ["collapse_selection", "insert_mode"]
"ret"     = ["insert_newline", "normal_mode"]

i         = "move_line_up"
I         = "extend_line_up"
"A-i"     = ["move_line_up"]
"A-I"     = "extend_line_up"
k         = "move_line_down"
K         = "extend_line_down"
"A-k"     = ["move_line_down"]
"A-K"     = "extend_line_down"
"A-j"     = ["move_prev_word_start", "collapse_selection"]
j         = "move_prev_word_start"
J         = "extend_prev_word_start"
"A-J"     = "extend_prev_word_start"
"A-l"     = ["move_next_word_start", "collapse_selection"]
l         = "move_next_word_start"
L         = "extend_next_long_word_start"
"A-L"     = "extend_next_word_start"
"A-u"     = "move_char_left"
u         = "move_char_left"
U         = "extend_char_left"
"A-U"     = "extend_char_left"
o         = "move_char_right"
"A-o"     = "move_char_right"
O         = "extend_char_right"
"A-O"     = "extend_char_right"
n         = "page_down"
p         = "page_up"
">"       = "repeat_last_motion"
","       = ["goto_line_end", "move_char_right"]
";"       = "goto_first_nonwhitespace"
"R"       = ["delete_selection", "paste_clipboard_before"]
esc       = "keep_primary_selection"
backspace = "delete_char_backward"
g         = { t = "goto_file_start", b = "goto_last_line", i = "hover", H = "extend_to_line_start" }
"["       = { "[" = "jump_backward" }
"]"       = { "]" = "jump_forward"  }
"space" = { "space" = "last_picker" }
"\\"    = "vsplit"
"|"     = "hsplit"
"'"     = "file_picker"
"tab"   = "indent"
"S-tab" = "unindent"

C-s       = ":w"
C-z       = "undo"
C-y       = "redo"
C-v       = "paste_clipboard_before"
C-S-v     = "paste_clipboard_after"
C-c       = "yank_main_selection_to_clipboard"
C-x       = ["yank_main_selection_to_clipboard", "delete_selection"]
"C-n"     = "search_next"
"C-p"     = "search_prev"
"C-r"     = [":reload-all"]
"A-q"     = "toggle_comments"
"a"       = "shell_pipe"
"S-a"     = "shell_pipe_to"
x         = "extend_line"
"V"       = ["goto_first_nonwhitespace", "extend_to_line_end"]
"b"       = "buffer_picker"
"Z"       = { i = ["scroll_up"], k = ["scroll_down"] }
"A-z"     = ":toggle-option soft-wrap.enable"

"w"       = "select_textobject_inner"
"W"       = "select_textobject_around"
"q"       = "collapse_selection"
"h"       = "no_op"

"t"       = "extend_till_char"
"f"       = "extend_next_char"
"T"       = "extend_till_prev_char"
"F"       = "extend_prev_char"

[keys.normal.e]
n = "goto_next_buffer"
p = "goto_previous_buffer"
j = "jump_view_left"
l = "jump_view_right"
i = "jump_view_up"
k = "jump_view_down"
x = ":bc"
X = "wclose"
J = "swap_view_left"
L = "swap_view_right"
I = "swap_view_up"
K = "swap_view_down"
q = [":bc", "wclose"]
t = "transpose_view"

[keys.normal.M]
i = [":append-output echo '%val{filename}' | python3 /home/murali/.config/scripts/markdown_image_insert.py"]
o = [ "yank_main_selection_to_clipboard", ":sh echo '%val{filename}' | python3 /home/murali/.config/scripts/markdown_file_open.py"]

t = ["extend_line", "yank_main_selection_to_clipboard", "delete_selection", ":w", ":append-output echo '%val{filename}' | python3 /home/murali/.config/scripts/markdown_insert_table.py"]
T = ["yank_main_selection_to_clipboard", "delete_selection", ":w", ":sh echo '%val{filename}' | python3 /home/murali/.config/scripts/markdown_format_table.py"]

[keys.insert]
"A-e"     = "normal_mode"
j         = { k = ["normal_mode"] }

"A-i"     = ["move_line_up"]
"A-I"     = ["extend_line_up", "normal_mode"]
"A-j"     = ["move_prev_word_start", "collapse_selection"]
"A-J"     = ["move_prev_word_start", "normal_mode"]
"A-k"     = ["move_line_down"]
"A-K"     = ["extend_line_down", "normal_mode"]
"A-l"     = ["move_next_word_start", "collapse_selection"]
"A-L"     = ["move_next_word_start", "normal_mode"]
"A-u"     = "move_char_left"
"A-U"     = "extend_char_left"
"A-o"     = "move_char_right"
"A-O"     = "extend_char_right"
"A-."     = "repeat_last_motion"
"A-n"     = "page_down"
"A-p"     = "page_up"
"A-,"     = ["goto_line_end", "move_char_right"]
"A-;"     = ["goto_first_nonwhitespace"]
"A-m"     = "no_op"
"A-M"     = "no_op"
"A-h"     = "no_op"
"A-H"     = "no_op"

C-z       = "undo"
C-y       = "redo"
C-v       = "paste_clipboard_before"
C-S-v     = "paste_clipboard_after"
C-c       = "yank_main_selection_to_clipboard"
C-x       = ["yank_main_selection_to_clipboard", "delete_selection"]
"C-space" = "completion"
"C-s"     = ["normal_mode", ":w"]
"tab"     = ["normal_mode", "indent"]
"S-tab"   = ["normal_mode", "unindent"]
"A-z"     = ["normal_mode", ":toggle-option soft-wrap.enable", "insert_mode"]

[keys.select]
","         = "goto_line_end"
";"         = "goto_first_nonwhitespace"
"backspace" = ["delete_selection", "normal_mode"]
esc         = ["normal_mode"]
i         = "extend_line_up"
k         = "extend_line_down"
j         = "extend_prev_word_start"
l         = "extend_next_word_start"
u         = "extend_char_left"
o         = "extend_char_right"
"C-n"     = "search_next"
"C-p"     = "search_prev"
"tab"   = "indent"
"S-tab" = "unindent"

